const fs = require('node:fs/promises');
const { chromium } = require('/workspaces/Langia.Online.Website/node_modules/playwright');
const out = '/tmp/langia-final-implementation/nav-qa';
const report = { desktop: {}, mobile: {}, footer: {}, pageErrors: [], failures: [] };
const assert = (value, message) => { if (!value) report.failures.push(message); };
const active = (page) => page.evaluate(() => ({ tag: document.activeElement?.tagName, text: document.activeElement?.textContent?.trim(), label: document.activeElement?.getAttribute('aria-label'), href: document.activeElement?.getAttribute('href') }));
const trackErrors = (page) => page.on('pageerror', error => report.pageErrors.push(error.message));
(async () => {
 const browser = await chromium.launch({ headless: true, args: ['--disable-dev-shm-usage'] });
 try {
  const desktopContext = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const page = await desktopContext.newPage(); trackErrors(page);
  await page.goto('http://127.0.0.1:4173/en', { waitUntil: 'networkidle' });
  const programs = page.locator('[data-navbar-primary]').getByRole('link', { name: 'Programs', exact: true });
  const panelId = await programs.getAttribute('aria-controls');
  assert(panelId, 'Updated desktop controlled menu was not served');
  const panel = page.locator(`[id="${panelId}"]`);
  await programs.hover();
  await page.waitForTimeout(250);
  const box = await programs.boundingBox();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height + 6, { steps: 18 });
  await page.waitForTimeout(700);
  report.desktop.slowHoverBridge = { expanded: await programs.getAttribute('aria-expanded'), visible: await panel.isVisible() };
  assert(report.desktop.slowHoverBridge.expanded === 'true' && report.desktop.slowHoverBridge.visible, 'Dropdown closed in hover gap');
  await page.screenshot({ path: `${out}/desktop-hover-bridge.png` });
  await panel.locator('a').first().hover();
  report.desktop.enteredPanel = await panel.isVisible();
  assert(report.desktop.enteredPanel, 'Dropdown closed while pointer entered panel');
  await page.mouse.move(1100, 520);
  await programs.focus();
  await page.keyboard.press('Tab');
  report.desktop.firstSubmenuFocus = await active(page);
  assert(await panel.evaluate(el => el.contains(document.activeElement)), 'Tab did not enter Programs submenu');
  await page.keyboard.press('Escape');
  report.desktop.escape = { expanded: await programs.getAttribute('aria-expanded'), visible: await panel.isVisible(), active: await active(page), inert: await panel.evaluate(el => el.inert) };
  assert(report.desktop.escape.expanded === 'false' && !report.desktop.escape.visible && report.desktop.escape.inert && report.desktop.escape.active.text === 'Programs', 'Escape did not close/inert dropdown and restore heading focus');
  await page.keyboard.press('Tab');
  report.desktop.afterEscapeTab = await active(page);
  assert(report.desktop.afterEscapeTab.href === '/en/about', 'Tab after Escape entered hidden submenu');
  await page.keyboard.press('Escape');
  await page.screenshot({ path: `${out}/desktop-keyboard-escape-tab.png` });
  await page.evaluate(() => window.scrollTo({ top: 1800, behavior: 'instant' }));
  await page.waitForTimeout(650);
  const actions = page.locator('[data-navbar-actions]');
  report.desktop.scrolledActions = await actions.evaluate(el => ({ opacity: getComputedStyle(el).opacity, transform: getComputedStyle(el).transform, pointerEvents: getComputedStyle(el).pointerEvents, box: { y: el.getBoundingClientRect().y, h: el.getBoundingClientRect().height } }));
  await actions.locator('a').first().focus();
  report.desktop.scrolledLogin = await active(page);
  await page.waitForTimeout(250);
  assert(report.desktop.scrolledActions.opacity === '1' && report.desktop.scrolledActions.pointerEvents !== 'none' && report.desktop.scrolledActions.box.y >= 0, 'Scrolled desktop action remains invisible/unusable');
  await page.screenshot({ path: `${out}/desktop-scrolled-login-focus.png` });
  const footer = page.locator('footer');
  await footer.scrollIntoViewIfNeeded();
  await page.waitForTimeout(300);
  report.footer.desktop = await footer.evaluate(el => ({ marginTop: getComputedStyle(el).marginTop, background: getComputedStyle(el).backgroundColor, transform: getComputedStyle(el).transform, transformedDescendants: Array.from(el.querySelectorAll('*')).filter(item => getComputedStyle(item).transform !== 'none').length, links: el.querySelectorAll('a').length, languageButtons: el.querySelectorAll('button[aria-pressed]').length, wordmark: Array.from(el.querySelectorAll('p')).some(item => item.textContent.trim() === 'Langia') }));
  assert(report.footer.desktop.marginTop === '0px' && report.footer.desktop.transform === 'none' && report.footer.desktop.transformedDescendants === 0, 'Footer retained overlap/transform effects');
  assert(report.footer.desktop.wordmark && report.footer.desktop.languageButtons === 3, 'Footer wordmark or language controls missing');
  await page.screenshot({ path: `${out}/desktop-footer.png` });
  await desktopContext.close();
  const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
  const mobile = await mobileContext.newPage(); trackErrors(mobile);
  await mobile.goto('http://127.0.0.1:4173/en', { waitUntil: 'networkidle' });
  const toggle = mobile.locator('header button[aria-controls]');
  await toggle.tap();
  await mobile.waitForTimeout(180);
  const mobilePanelId = await toggle.getAttribute('aria-controls');
  const mobilePanel = mobile.locator(`[id="${mobilePanelId}"]`);
  report.mobile.opened = { expanded: await toggle.getAttribute('aria-expanded'), overflow: await mobile.evaluate(() => document.body.style.overflow), active: await active(mobile) };
  assert(report.mobile.opened.expanded === 'true' && report.mobile.opened.overflow === 'hidden' && report.mobile.opened.active.text === 'Programs', 'Mobile open/focus/scroll lock failed');
  await mobile.screenshot({ path: `${out}/mobile-menu-open.png` });
  const count = await mobilePanel.locator('a[href], button:not([disabled]), [tabindex="0"]').count();
  report.mobile.focusWalk = [];
  for (let i=0; i<count+3; i++) {
   await mobile.keyboard.press('Tab');
   const state = await mobile.evaluate((id) => ({ text: document.activeElement?.textContent?.trim(), label: document.activeElement?.getAttribute('aria-label'), allowed: document.getElementById(id)?.contains(document.activeElement) || document.activeElement?.getAttribute('aria-controls') === id }), mobilePanelId);
   report.mobile.focusWalk.push(state);
   assert(state.allowed, `Mobile focus escaped on forward Tab ${i+1}`);
  }
  await toggle.focus();
  await mobile.keyboard.press('Shift+Tab');
  report.mobile.reverseWrap = await active(mobile);
  assert(report.mobile.reverseWrap.text === 'Log in', 'Shift+Tab from mobile toggle did not reach last panel link');
  report.mobile.scrollToActions = await mobilePanel.evaluate(el => { const link = el.querySelectorAll('a')[el.querySelectorAll('a').length - 1]; const panelBox = el.getBoundingClientRect(); const linkBox = link.getBoundingClientRect(); return { scrollTop: el.scrollTop, scrollHeight: el.scrollHeight, clientHeight: el.clientHeight, panelBottom: panelBox.bottom, linkBottom: linkBox.bottom, linkTop: linkBox.top, windowHeight: innerHeight, overflowY: getComputedStyle(el).overflowY }; });
  assert(report.mobile.scrollToActions.scrollTop > 0 && report.mobile.scrollToActions.linkBottom <= report.mobile.scrollToActions.panelBottom && report.mobile.scrollToActions.linkBottom <= report.mobile.scrollToActions.windowHeight, 'Mobile menu cannot scroll to all action links');
  await mobile.screenshot({ path: `${out}/mobile-menu-actions-focused.png` });
  await mobile.keyboard.press('Tab');
  report.mobile.forwardWrap = await active(mobile);
  assert(report.mobile.forwardWrap.label === 'Close menu', 'Tab from last mobile link did not wrap to toggle');
  await mobile.keyboard.press('Escape');
  await mobile.waitForTimeout(120);
  report.mobile.escape = { expanded: await toggle.getAttribute('aria-expanded'), active: await active(mobile), overflow: await mobile.evaluate(() => document.body.style.overflow) };
  assert(report.mobile.escape.expanded === 'false' && report.mobile.escape.active.label === 'Open menu' && report.mobile.escape.overflow !== 'hidden', 'Mobile Escape did not restore toggle focus/body scroll');
  await mobile.screenshot({ path: `${out}/mobile-menu-escape.png` });
  await mobile.locator('footer').scrollIntoViewIfNeeded();
  await mobile.waitForTimeout(250);
  report.footer.mobile = await mobile.locator('footer').evaluate(el => ({ marginTop: getComputedStyle(el).marginTop, scrollWidth: document.documentElement.scrollWidth, viewportWidth: innerWidth, narrowTargets: Array.from(el.querySelectorAll('a,button')).filter(item => item.getBoundingClientRect().height < 43.9).map(item => ({ text: item.textContent.trim(), h: item.getBoundingClientRect().height })) }));
  assert(report.footer.mobile.scrollWidth === report.footer.mobile.viewportWidth && report.footer.mobile.narrowTargets.length === 0, 'Mobile footer overflow or targets below 44px');
  await mobile.screenshot({ path: `${out}/mobile-footer.png` });
  await mobile.setViewportSize({ width: 844, height: 390 });
  await mobile.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
  await toggle.tap();
  await mobile.waitForTimeout(150);
  const landscapePanel = mobile.locator(`[id="${mobilePanelId}"]`);
  await landscapePanel.locator('a').last().focus();
  report.mobile.landscapeActions = await landscapePanel.evaluate(el => { const rect = el.getBoundingClientRect(); const linkRect = el.querySelectorAll('a')[el.querySelectorAll('a').length - 1].getBoundingClientRect(); return { scrollTop: el.scrollTop, panelBottom: rect.bottom, actionBottom: linkRect.bottom, viewportHeight: innerHeight }; });
  assert(report.mobile.landscapeActions.actionBottom <= report.mobile.landscapeActions.viewportHeight && report.mobile.landscapeActions.scrollTop > 0, 'Landscape menu cannot reach CTA actions');
  await mobile.screenshot({ path: `${out}/mobile-landscape-actions.png` });
  await landscapePanel.getByRole('link', { name: 'Start', exact: true }).tap();
  await mobile.waitForURL('**/en/contact');
  report.mobile.actualStartTapDestination = new URL(mobile.url()).pathname;
  assert(report.mobile.actualStartTapDestination === '/en/contact', 'Mobile menu Start tap failed to reach existing contact route');
  await mobileContext.close();
  assert(report.pageErrors.length === 0, 'Browser page errors detected');
 } catch (error) { report.failures.push(error.stack); }
 await fs.writeFile(`${out}/report.json`, JSON.stringify(report, null, 2));
 await browser.close();
 console.log(JSON.stringify(report, null, 2));
 if (report.failures.length) process.exitCode=1;
})();
